.
.
.TH QOOB\-FLASHER 1  "January 2009" "Qoob Pro" "Flasher utility"
.
.
.SH NAME 
qoob-flasher \- Nintendo Gamecube Qoob Pro mod-chip flasher utility
.
.
.SH SYNOPSIS
.na
.nh
.B qoob\-flasher [OPTIONS]... [FILE]
.ad
.hy
.
.
.SH DESCRIPTION
.B qoob\-flasher
is a flasher tool for Nintendo Gamecube Qoob Pro 
.br
mod\-chip. qoob\-flasher supports listing, erasing, reading 
.br
and writing flash slots. Supported file formats for writing 
.br
are GCB, ELF and DOL. Reading is GCB only.
.
.
.
.TP
.B \-w, \-\-write\=SLOT
Write given GCB file to flash. Have to use. One of the
.br
.B\-d,\-\-dol, \-l,\-\-elf
or
.B \-q.\-\-qoob 
must be used with write
.
.TP
.B \-r, \-\-read=SLOT
Read from flash to given file. Format is always GCB
.
.TP
.B \-e, \-\-erase=SLOT
Erase application in flash
.
.TP
.B \-f, \-\-force\-erase=SLOT
Erase one slot
.
.TP
.B \-l, \-\-elf
ELF file format to be written
.
.TP
.B \-d, \-\-dol
DOL file format to be written
.
.TP
.B \-q, \-\-qoob
GCB or Qoob Config file format to be written
.
.TP
.B \-v, \-\-verbose
Gives more information what happens when managing flash
.
.TP
.B \-s, \-\-slot-list
Prints slot list after write or erase
.
.TP
.B \-h, \-\-help
Display help and exits
.
.SH EXAMPLES
.
.PP
.TP
.B Show what is flashed.
qoob\-flasher
.
.TP
.B Read bios from the flash and save it to /tmp.
qoob\-flasher \-r0 /tmp/qoob\-bios.gcb
.
.TP
.B Erase qoob\-bios from flash
qoob\-flasher \-e0
.
.TP
.B Write bios to the flash.
qoob\-flasher \-q \-w0 /tmp/qoob\-bios.gcb.
.
.TP
.B Write bios to the flash and list it after flashing.
qoob\-flasher \-s \-q \-w0 /tmp/qoob\-bios.gcb.
.
.TP
.B Read config from the flash and save it to /tmp.
qoob\-flasher \-r31 /tmp/qoob\-config.gcb
.
.TP
.B Erase qoob\-config from flash
qoob\-flasher \-e31
.
.TP
.B Write Qoob config to the flash.
qoob\-flasher \-q \-w31 /tmp/qoob\-config.gcb.
.
.TP
.B Read config from the flash and save it to /tmp. Gives little information about where is written and is this success.
qoob\-flasher \-v \-r31 /tmp/qoob\-config.gcb
.
.TP
.B Read config from the flash and save it to /tmp. Gives also information about progress of the command.
qoob\-flasher \-vv \-r31 /tmp/qoob\-config.gcb
.
.
.
.SH AUTHOR 
Written by Joni Valtanen.
.
.
.SH COPYRIGHT
Copyright  ©  2009  Joni  Valtanen.  License  GNU  GPL  version  2  or
.br
later <http://gnu.org/licenses/gpl.html>.  This  is  free  software:  
.br
you  are  free to change and redistribute it. There is NO WARRANTY,
.br
to the extent permitted by law.
.
