#!/bin/sh

if [ "$1" = configure ]; then
  if [ -x "/etc/init.d/udev" -a -x "/usr/sbin/invoke-rc.d" ]; then
     echo "Restarting udev..."
     invoke-rc.d udev restart
  fi

  if [ -x "/sbin/modprobe" -a -x "/sbin/rmmod" ]; then
     echo "Reloading usbhid module..."
     rmmod usbhid
     modprobe usbhid
     echo "Add your libqoob user to plugdev group."
  fi

  if [ -x "/sbin/ldconfig" ]; then
     ldconfig
  fi
fi
